<?php
$collection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
// if no products are currently featured, display some text
if (!$collection->getSize()) :
    ?>
    <p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>
<?php else : ?>
<div class="titlenew"><h2 class="subtitle"><span><?php echo $this->__('Featured Products') ?></span></h2></div>
<div class="clear"></div>
<?php
$counter=1;
$_collectionSize = $collection->count();
$_columnCount = 5;
$i = 0;
$f=0;
foreach ($collection as $_product) :
$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
?>
<?php if ($i++%$_columnCount==0): ?>
<div class="category-products">
    <ul class="products-grid row">
        <?php endif ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>  col-md-3 col-sm-3 col-xs-6">
            <div class="label-featured">Featured</div>
            <div class="item-container img-thumbnail">
                <div class="item-flipper">
                    <div class="item-front">
                        <!-- front content -->
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,245); ?>"
                                                      alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive" />
                        </a>
                    </div>
                </div>
            </div>

            <h3 class="panel-title product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
            <div class="pull-left"> <?php echo $this->getPriceHtml($_product, true) ?> </div>
            <div class="pull-right">
                <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-warning btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                <?php else: ?>
                    <p class="btn btn-default availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            </div>
        </li>
        <?php if($counter==5){break;} $counter++; ?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>

    <?php endif ?>
    <?php $f--; endforeach; ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif ?>
</div>