<?php
$_columnCount = 5;
$_products = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if ($_products && $_products->getSize()): ?>
    <div class="new-product product-special">
        <div class="titlenew"><h2 class="subtitle"><span><?php echo $this->__('Sale off') ?></span></h2></div>
        <div class="clear"></div>
        <?php $s=0;$i=0; foreach ($_products->getItems() as $_product): ?>
                <?php if ($i++==0): ?>
                    <div  class="special-products flexslider category-products">
                    <ul class="slides products-grid row">
                <?php endif ?>
                            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> col-sm-3 col-xs-6">
                            <div class="item-container img-thumbnail">
                                <div class="item-flipper">
                                    <div class="item-front">
                                        <!-- front content -->
                                        <a href="<?php echo $_product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                           class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,245); ?>"
                                                                      alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive" />
                                        </a>
                                    </div>

                                    <div class="item-back">
                                        <!-- back content -->
                                        <div class="book-info">
                                            <div class="h4"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></div>

                                            <div class="short-description"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div>
                                        </div>
                                        <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="btn btn-block btn-success"><?php echo $this->__('Book Details')?></a></p>
                                    </div>
                                </div>
                            </div>

                            <h3 class="panel-title product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                            <div class="pull-left"> <?php echo $this->getPriceHtml($_product, true) ?> </div>
                            <div class="pull-right">
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-warning btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                                <?php else: ?>
                                    <p class="btn btn-alert availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                        </li>
                <?php if ($i==0 || $i==count($_products)): ?>
                    </ul>
                    </div>
                <?php endif ?>
            <?php $s--; endforeach; ?>
    </div>
<?php endif ?>
<script type="text/javascript">
    // Can also be used with $(document).ready()
    $j(window).load(function() {
        $j('.special-products.flexslider').flexslider({
            animation: "slide",
            animationLoop: false,
            itemWidth: 270,
            itemMargin: 0,
            minItems: 2,
            maxItems: 4
        });
    });
</script>